version: '3.2'

services:
  dapptools:
    restart: unless-stopped
    image: vulcanize/dapptools:v0.29.0-statediff-0.0.2
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"

  db:
    restart: always
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_public"
      POSTGRES_PASSWORD: "password"
    volumes:
     - vulcanizedb_db_data:/var/lib/postgresql/data
    expose:
     - "5432"
    ports:
     - "127.0.0.1:8079:5432"

  eth:
    depends_on:
      - db
    build:
      context: ./
      cache_from:
       - alpine:latest
       - golang:1.12.4
      dockerfile: ./Dockerfile
    environment:
      VDB_COMMAND: "sync"
      DATABASE_NAME: "vulcanize_public"
      DATABASE_HOSTNAME: "db"
      DATABASE_PORT: 5432
      DATABASE_USER: "vdbm"
      DATABASE_PASSWORD: "password"
    ports:
     - "127.0.0.1:8080:8080"
     - "127.0.0.1:8081:8081"

volumes:
  vulcanizedb_db_data:
