{
 "title": "ipld-eth-indexer",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_blocks[1m])"
    }
   ]
  },
  {
   "title": "Receipts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_receipts[1m])"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_transactions[1m])"
    }
   ]
  },
  {
   "title": "Postgres transaction commit duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_stats_t_postgres_commit_sum[1m])/rate(ipld_eth_indexer_stats_t_postgres_commit_count[1m])"
    }
   ]
  },
  {
   "title": "Payload decoding time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_stats_t_payload_decode_sum[1m])/rate(ipld_eth_indexer_stats_t_payload_decode_count[1m])"
    }
   ]
  },
  {
   "title": "Time spent waiting for free postgres",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_stats_t_free_postgres_sum[1m])/rate(ipld_eth_indexer_stats_t_free_postgres_count[1m])"
    }
   ]
  },
  {
   "title": "Header processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_stats_t_header_processing_sum[1m])/rate(ipld_eth_indexer_stats_t_header_processing_count[1m])"
    }
   ]
  },
  {
   "title": "Uncle processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_indexer_stats_t_uncle_processing_sum[1m])/rate(ipld_eth_indexer_stats_t_uncle_processing_count[1m])"
    }
   ]
  }
 ]
}